name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out Github Actions
on: [push]
jobs: 
   Explore-GitHub-Actions:
      runs-on: ubuntu-latest
      steps:
         - name: Primeiro Steps
           run:  echo "The job was automatically triggered by a ${{ github.event_name }} event."
         - name: Segundo Steps 
           run: echo "A ação esta sendo gerado no Sistema Operacional ${{ runner.os }} "
         - name: Terceiro Steps  
           run: echo "O repositorio que esta sendo utilizada e o ${{ github.repository }}"
         - name: Ultimo Steps 
           run: echo "Criando em 14/09/2026"
